### ISSUE TITLE
SC7A20 accelerometer

### ISSUE THREAD

**Issue by goddade** [atc1441/ATCwatch#18]
The model of my watch is p8b, stock firmware is MOY-TIN5.
The accelerometer of ATCwatch firmware does not work.
I found that the accelerometer chip of p8b is not bma421 but SC7A20.
Is there a SC7A20 version of ATCwatch firmware?

**Comment by atc1441** [comment]
Hey, so far not, there is active Discussion going on in the Discord server https://discord.com/invite/TRktBnv

That Accl does not have integrated step counting so there is a real algo needed to use it thats a big step but needed as more and more Watches have the the SC7A20

**Comment by goddade** [comment]
I want to write a driver for SC7A20, but I don't know the configurations of BMA421.
For example, data resolution, full scale, work mode, ODR, function of INT1.

**Comment by atc1441** [comment]
Here are the configs i use. 
https://github.com/atc1441/ATCwatch/blob/0dd3138d10d5c8f1a776ad1b7f1d4819d686e46f/ATCwatch/accl.cpp#L36

The Interrupt function is not used of the BMA421 as it has no usefull features for the usecases.
