### ISSUE TITLE
Text from bootloader (ATCnetz.de) faintly visible on the 

### ISSUE THREAD

**Issue by wilkgr76** [atc1441/ATCwatch#5]
The red square and ATCnetz.de text from the bootloader is faintly visible beneath the grey background:

![image](https://user-images.githubusercontent.com/12093476/85943957-d6d84a80-b976-11ea-91fd-96bd2ec887c2.png)

**Comment by atc1441** [comment]
Hi. That will go away over time(minutes not days)

Its kind of a burned in image as it was shown for so long in the bootloader.

But as it is only an ips lcd display it does recover.

**Comment by wilkgr76** [comment]
Ahhhh I see. I didn't realised that it was as a result of the LCD. My apologies!
