### ISSUE TITLE
Colliding name in the GIT

### ISSUE THREAD

**Issue by sgungnir** [atc1441/ATCwatch#7]
menu_animation was used with upper and lower case at different points and it is now causing a collision when cloning after July 5th (the new settings screen commit):

Cloning into 'ATCwatch'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 649 (delta 1), reused 0 (delta 0), pack-reused 641Receiving objects:  89% (578/649)
Receiving objects: 100% (649/649), 558.77 KiB | 1.64 MiB/s, done.
Resolving deltas: 100% (319/319), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'ATCwatch/menu_Animation.h'
  'ATCwatch/menu_animation.h'

**Comment by atc1441** [comment]
Thank you for that.

The lower case was a leftover on github and i deleted it just now, maybe its still cached on github servers but it is resolved.

So the lower case version can simple be ignored/deleted
