### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sgungnir** [atc1441/ATCwatch#8]
font57.h is missing, also, the inc_tick function is not found. (I assume there is a missing file or it is in a changed file that was not commited).

**Comment by atc1441** [comment]
EDIT. 

It was indeed wrong. i uploaded a wrong display.cpp and display.h from an older version. 

this is now fixed

compiles fine now after testing.

I shouldn't do updates so late :D

Thank you for the issue

**Comment by sgungnir** [comment]
Thanks for that ! Working late at night is fun, but sometimes dangerous :) What software are you using for source control ? do you just manually upload the changed files? or are you using the git client on your machine and making commits ? (just curious)
