### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by PuceBaboon** [atc1441/ATCwatch#9]
Aaron,

   Nice project!  Thanks for all of the work you've put in on this.

   There's a very minor typo in the string at line 76 in bettery.cpp.  It shows as "Battery Emtpy", but should be "Battery Empty".  Unfortunately, it shows up in the photo's that Jean-Luc used in his article "https://www.cnx-software.com/2020/07/22/atcwatch-arduino-firmware-pinetime-colmi-p8-da-fit-smartwatches/".

   Keep up the brilliant work (on your ESP32 projects, too).

   Very best wishes from Japan,

                                   -John-

**Comment by atc1441** [comment]
Oh thank you very much.

Just fixed that.

Have a nice day
